### ISSUE TITLE
Select Source Folder not working in Windows 11 22H2

### ISSUE THREAD

**Issue by rgmorato** [sibranda/Powershell#1]
Caro @sibranda .

Aparentemente, ao clicar em Source Folder, não consigo navegar nas pastas do computador. Aparece apenas a pasta Desktop e não há para onde mais ir.

**Comment by sibranda** [comment]
Olá amigo, muito obrigado pelo feedback.

Testei no Windows 11 e funcionou:
<img width="570" alt="image" src="https://user-images.githubusercontent.com/62342144/200072610-c9f73424-1fc2-4e71-ad4a-7306d325c0b9.png">

Pode ser permissão por aí?

Veja se é possível testar em outra máquina ou com outro usuário e me diz.

Abraço 👍
